version: '3'

services:
  db:
    image: postgres:11
    container_name: test-db
    restart: always
    env_file:
      - ./db.env # uses POSTGRES_DB and POSTGRES_PASSWORD to create a fresh db with a password when first run
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # only used to upload DB dump:
      # - ./backup:/tmp/backup

  api:
    container_name: test-api
    restart: 'no'
    build:
      context: .
      args:
        NODE_ENV: development
    depends_on:
      - db
    volumes:
      - ./:/usr/src/api
      - ./node_modules:/usr/src/api/node_modules
    command: /bin/sh -c 'echo "Starting" && npm install && npm run dev'
